import { ActivityCategory } from './activity';
import { GoalStatus } from './goal';
import { PeriodStatus } from './accounting';

export const ErrorCodes = {
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  RBAC_ROLE_DENIED: 'RBAC_ROLE_DENIED',
  USER_EMAIL_DUPLICATE: 'USER_EMAIL_DUPLICATE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_PASSWORD_INVALID: 'USER_PASSWORD_INVALID',
  ACTIVITY_CATEGORY_INVALID: `ACTIVITY_CATEGORY_INVALID:${Object.values(ActivityCategory).join('|')}`,
  ACTIVITY_NOT_FOUND: 'ACTIVITY_NOT_FOUND',
  FACTOR_NOT_FOUND: 'FACTOR_NOT_FOUND',
  GOAL_STATUS_INVALID: `GOAL_STATUS_INVALID:${Object.values(GoalStatus).join('|')}`,
  GOAL_NOT_FOUND: 'GOAL_NOT_FOUND',
  AUDIT_LOG_FAILED: 'AUDIT_LOG_FAILED',
  PERIOD_FORMAT_INVALID: 'PERIOD_FORMAT_INVALID',
  PERIOD_NOT_FOUND: 'PERIOD_NOT_FOUND',
  PERIOD_CLOSED: `PERIOD_CLOSED:${Object.values(PeriodStatus).join('|')}`,
  PERIOD_ALREADY_CLOSED: 'PERIOD_ALREADY_CLOSED',
  PERIOD_NOT_CLOSED: 'PERIOD_NOT_CLOSED',
  PERIOD_CLOSE_CONFLICT: 'PERIOD_CLOSE_CONFLICT',
  PERIOD_REOPEN_REASON_REQUIRED: 'PERIOD_REOPEN_REASON_REQUIRED',
  PERIOD_VERSION_NOT_FOUND: 'PERIOD_VERSION_NOT_FOUND',
  PERIOD_LOCK_CONFLICT: 'PERIOD_LOCK_CONFLICT',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  DATABASE_FAILED: 'DATABASE_FAILED'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

